### ISSUE TITLE
Not redirecting to billing

### ISSUE THREAD

**Issue by slashcart** [Kyon147/laravel-shopify#118]
I am using kyyon147/Laravel-Shopify version 18. user is not redirecting for billing approval to Shopify page.

here is how i am using link for billing

{{ route('billing', ['plan' =>3,'shop' => Auth::user()->name, 'host' =>base64_encode(Auth::user()->name),'token'=>request()->get('token')]) }}

but one i click select plan button its shows blank page in same iframe
![image](https://user-images.githubusercontent.com/113967682/225549044-3eeafd46-fa8a-4619-b638-fe8ea5f657e3.png)

one more thing  redirection is not working in app if I don't pass token parameters and also not with URL::tokenRoute 
@Kyon147 
Thanks in Advance

**Comment by Kyon147** [comment]
@slashcart 

It looks like your host value is wrong, you don't set this yourself - you need to grab it from the session which Shopify will pass on the initial page load.

If you are using blade templates, it is your job to pass that host value after the initial page load. 

You are probably seeing this screen because your host value is incorrect.

**Comment by slashcart** [comment]
how to get host from session

**Comment by Kyon147** [comment]
You can try the token redirect helper method, the details are here https://github.com/Kyon147/laravel-shopify/wiki/Authentication-Process#links--routing

Closing this ticket as it is not a package issue.

**Comment by slashcart** [comment]
ok
