### ISSUE TITLE
Duplicate entry 'shop@xxx.myshopify.com' for key 'users_email_unique'

### ISSUE THREAD

**Issue by alexiovay** [Kyon147/laravel-shopify#143]
Hello,

I want to create a new Shopify merchant app. After testing to create my first subscription I get this error message:

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'shop@xxx.myshopify.com' for key 'users_email_unique'`

I'm not quite aware about the whole flow of laravel-shopify but it seems `InstallShop.php` tries to create a new user and therefor this error occurs.

It is normal that a new user gets created on the first visit, I assume? I followed the installation wiki and trying to implement Stripe to get payments of merchants for this app.

**Comment by Kyon147** [comment]
@xeisu it sounds like you are trying to create your own billing using Stripe, rather than Shopify's built-in billing.

It's not something the package is set up to do, but there can only be one shop record in the users table, you are trying to create another one from the looks of it. So you need to change your logic, so that you are not trying to create a shop that already exists.
