### ISSUE TITLE
Tried to login from login form: Redirecting to a wrong URL (missing shop) 

### ISSUE THREAD

**Issue by ecomzier** [Kyon147/laravel-shopify#188]
Hi,

My app has a login form which default package login form. I entered my store URL which is "discountly6.myshopify.com" to log into my app dashboard directly Instead I first go to Shopify, open the Shopify apps and then I open my installed app.

I got this error: The package login form has redirected me to a URL that does not have a shop domain at the start of the URL.

<img width="939" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/87474497/bb757f28-71c1-4438-97dc-a14f3cdef3df">

It redirected to this

<img width="1435" alt="image" src="https://github.com/Kyon147/laravel-shopify/assets/87474497/ead6538f-58b5-44d4-a14e-085294e0bd48">

**Comment by Kyon147** [comment]
The login page was removed this package a few versions back, so I assume you are on an older package version which is not supported.

Shopify don't allow the login pages anymore I believe, which is why it was removed a year or more ago.

Closing as not a package issue, please open a discussion or ask in the Discord in the app-coding-help channel.
