### ISSUE TITLE
Annual plans are not working as expected 

### ISSUE THREAD

**Issue by Kyon147** [Kyon147/laravel-shopify#24]
Annual plan is not working when setting it up correctly in the database.

![image](https://user-images.githubusercontent.com/32519106/208643364-78818d17-9853-4643-926e-6cfabfd67531.png)

**Comment by tinhphantrong0612** [comment]
Might not be the right cause but price = 0 is not allowed in normal recurring charge.
It might work fine in monthly because with `capped_amount` and `terms`, it will turn into recurring charge with a usage charge will be attached to it in the future. Remove `capped_amount` and `terms`, it will result an error: `422 Unprocessable Entity response: {\"errors\":{\"price\":[\"must be greater than zero\"]}}`. More can be found here: [https://shopify.dev/api/admin-rest/2022-10/resources/usagecharge](url) in "Charging for usage only" section
But with graphql, which we use for creating annual charge. It currently create a normal recurring charge only. So price must be greater than 0.

**Comment by Kyon147** [comment]
I have found the issue to this, when using the graphQL subscriptionCreate, your app must have selected the right distribution, which needs to be Shopify App Store.

![image](https://user-images.githubusercontent.com/32519106/209971529-85ac94ca-93eb-4b5f-9dbb-d621f782528f.png)

Once this step has been completed, the annual charge will work as intended.

![image](https://user-images.githubusercontent.com/32519106/209971636-728f580d-3cab-49cc-a415-e893df10a7e2.png)
