### ISSUE TITLE
Not able to configure the Shopify Theme App Extension with latest version of Laravel Shopify package

### ISSUE THREAD

**Issue by prashantk3** [Kyon147/laravel-shopify#253]
### Discussed in https://github.com/Kyon147/laravel-shopify/discussions/252

<div type='discussions-op-text'>

<sup>Originally posted by **prashantk3** December 26, 2023</sup>
@Kyon147, 
I need to setup the Theme app extension as per Shopify recommendation. I already followed the steps as mentioned on https://github.com/gnikyt/laravel-shopify/wiki/How-to-create-App-Extension . But unfortunately i am not able to create the Theme App Extension and i am getting the message as attached screen 
![Error - Auto Open Partner login](https://github.com/Kyon147/laravel-shopify/assets/71825270/262b2830-77ec-4783-8c4f-537aaef2ca86)
  
and when i tried to open the partner link manually i am getting the error **"127.0.0.1 refused to connect."**, also attached the screen for the error. 
![Error - Manual Open partner ](https://github.com/Kyon147/laravel-shopify/assets/71825270/33b61555-a2e4-4e56-b90b-fe699565ee9d)

Please suggest how to configure the new Theme App Extension with an Existing Shopify Non-Embedded App. Please help.</div>

**Comment by enmaboya** [comment]
just follow the official documentation

https://shopify.dev/docs/apps/online-store/theme-app-extensions/getting-started

**Comment by Kyon147** [comment]
@prashantk3 this looks like an issue with the set up of the extension via the Shopify rather than anything to do with the package. As such, there's not a lot I'd be able but based on your screenshot I'd say the shopify dev server is not running, so I'd look at your terminal for errors. 

Your first screenshot says the auth is timing out, so I'd fix that first as without the authentication to Shopify, the extension won't be able to connect.

Going to close this ticket as it is not a package issue but keep replying in here on your progress.
