### ISSUE TITLE
Missing Auth Url on installation

### ISSUE THREAD

**Issue by Ansari-techs** [Kyon147/laravel-shopify#260]
![WhatsApp Image 2024-01-06 at 4 33 01 PM](https://github.com/Kyon147/laravel-shopify/assets/124798410/ee6a9a32-e277-4367-94b3-6ef458390ef4)

**Comment by SpiekerJozef** [comment]
![image](https://github.com/Kyon147/laravel-shopify/assets/97231447/c758510f-5b43-4e07-b4ea-6368efe925c2)

**Comment by SpiekerJozef** [comment]
Same here

**Comment by M4tini** [comment]
Same here, using release [v19.2.0](https://github.com/Kyon147/laravel-shopify/releases/tag/v19.2.0)

```
Osiset\ShopifyApp\Exceptions\MissingAuthUrlException:
Missing auth url

  at /opt/app/vendor/kyon147/laravel-shopify/src/Traits/AuthController.php:55
```

**Comment by nebsta9** [comment]
i had the same issue, I manage to solve this by adding my store password into the users table in the database

**Comment by Kyon147** [comment]
Missing auth URL usually means the set up is not correctly configured i.e. your api keys or urls.

**Comment by Ansari-techs** [comment]
> Missing auth URL usually means the set up is not correctly configured i.e. your api keys or urls.

This exception show on some Shopify themes if I change store theme and then install again so it's work correctly. Why this show on some themes?

**Comment by Ansari-techs** [comment]
@Kyon147 any update?

**Comment by igorrozzu** [comment]
@Kyon147 @Ansari-techs Have the same error just on first install. All keys in config are set up properly
[v19.2.0] on Laravel 10 / PHP 8.3.1 / Shopify API version 2023-10
![screen-2024-01-27-14-13-44](https://github.com/Kyon147/laravel-shopify/assets/17320874/48383327-bad6-4a3d-911f-0d7b2b3da750)

**Comment by Kyon147** [comment]
I'll try a new install and see if the issue happens for me too

**Comment by Kyon147** [comment]
Starting a new docker image for one of my apps I did run into this issue. 

For me it was broken migrations, so can you check you are running any migrations for your app that you may have missed in the package.

**Comment by M4tini** [comment]
After some debugging I came to the same conclusion and running the migration ([according to the upgrade guide](https://github.com/Kyon147/laravel-shopify/wiki/Upgrading#v18xx--v1900)) fixed it.

I saw in my added debug logs that `InstallShop` encountered a SQL exception, but the final error we all encountered is very obscure. This is caused by InstallShop having a try/catch that ignores the thrown Exception:
https://github.com/Kyon147/laravel-shopify/blob/master/src/Actions/InstallShop.php#L113

The combination of returned values `'completed' => false` and `'url' => null` is not expected by the rest of the app, resulting in the `AuthController` trying to redirect to an url that is `null`.

**Comment by Kyon147** [comment]
Sounds like the same issue, seems the exception is getting silenced up the stack. So would be a good to make this more visible in the future. I'll create an issue for it.

**Comment by haseebsoftwreng** [comment]
Hey developers, I hope you're all doing well. I'm encountering the same issue. In my case, I'm using ngrok. Instead of using the ngrok URL in the app, I'm using the local server URL http://127.0.0.1:8000. When I changed the URL in the environment to the local server instead of the ngrok server provided URL, my webhook started processing successfully. Try this approach, it should work for you too.
