### ISSUE TITLE
Show blank page after app install in my store

### ISSUE THREAD

**Issue by santoshwebinno** [Kyon147/laravel-shopify#296]
*TypeError: Cannot read properties of undefined (reading 'getSessionToken').*
![Screenshot 2024-04-12 152021](https://github.com/Kyon147/laravel-shopify/assets/3539524/a1bdb7ee-4722-4441-8e25-ecbac5a72194)

my package.json
"require": {
        "php": "^8.0",
        "fruitcake/laravel-cors": "^2.0.5",
        "guzzlehttp/guzzle": "^7.2",
        "kyon147/laravel-shopify": "^21.0",
        "laravel/framework": "^9.0",
        "laravel/sanctum": "^2.14",
        "laravel/tinker": "^2.7"
    },

**Comment by GDeep3013** [comment]
Hey there i am facing the some strange issue here. App stopped working suddenly. 
and it show the blank page. Please help me to resolve it. 

![image](https://github.com/Kyon147/laravel-shopify/assets/23520280/a7e2b2b2-3bd2-4fe7-a222-8ff67cdeb189)

i tried to upgrade to shopify app bridge 4.* but still app showing the same errors. 

![image](https://github.com/Kyon147/laravel-shopify/assets/23520280/516379c1-91a6-4cf8-a4a6-92b54921a1b3)

**Comment by tezcanali** [comment]
This situation is currently caused by a problem with the Unpkg CDN service.

If you replace the codes added via unpkg.com in shopify-app.php file and some parts of the package with a different cdn service, the problem will be fixed.

Or if you wait for a while, the problem will be fixed again when unpkg opens.

**Comment by tezcanali** [comment]
<img width="1056" alt="Screenshot 2024-04-12 at 14 58 14" src="https://github.com/Kyon147/laravel-shopify/assets/57041355/ff665ced-62d7-4876-b974-2de34012c5a4">

https://unpkg.com/@shopify/app-bridge

This situation is currently caused by a problem with the Unpkg CDN service.

If you replace the codes added via unpkg.com in shopify-app.php file and some parts of the package with a different cdn service, the problem will be fixed.

Or if you wait for a while, the problem will be fixed again when unpkg opens. 

@GDeep3013 @santoshwebinno

**Comment by santoshwebinno** [comment]
@tezcanali Thank you so much, Its work for me

**Comment by mdzahid-pro** [comment]
In my case i have resolve this issue by uninstalling the app and reinstall the app my issue was resolved
