### ISSUE TITLE
"Shopify App Outdated" for v12.1

### ISSUE THREAD

**Issue by APdevelopments** [Kyon147/laravel-shopify#50]
I build an app using version 12.1 and Laravel 5.8 and I got error when new users login to my app "Shopify App Outdated"

I found a few fix for version 17 but there is no any article how to solve that problem in v12.1

My AppBridge is:

```
 @if(config('shopify-app.appbridge_enabled'))
            <script src="https://unpkg.com/@shopify/app-bridge{{ config('shopify-app.appbridge_version') ? '@'.config('shopify-app.appbridge_version') : '' }}"></script>
            <script>
                var AppBridge = window['app-bridge'];
                var createApp = AppBridge.default;
                var app = createApp({
                    apiKey: '{{ config('shopify-app.api_key') }}',
                    shopOrigin: '{{ Auth::user()->name }}',
                    forceRedirect: true,
                });
            </script>

            @include('shopify-app::partials.flash_messages')
        @endif
```

I was trying to replace    shopOrigin: '{{ Auth::user()->name }}', with admin.shopify.com but error is the same

If I make version non-embeded version I will get rid of these messeage because my uninstall rate is so high with error message...

Please help!

* Package Version: v12.1
* Laravel Version: v5.8
* PHP Version: v7.3

**Comment by Kyon147** [comment]
v12 and v17 are so far apart, there is no direct fix for you apart from you either upgrading or finding your own solution for your outdated codebase. 

The issue is `shopOrigin` is being replaced with `host` but there are a few places in the code base that have to be updated. Such as billing routes. 

You will want to look at the last couple patches to give you an idea but that will only be part of the solution, there are likely to be other issues because you are 5 major version behind.

**Comment by APdevelopments** [comment]
What will be quick fix - to make my app non-embedable ?

**Comment by Kyon147** [comment]
I can't tell you, non-embed is not supported by this package at the moment on v17, so upgrading to the latest version won't help you.

You best bet is to fix the issue on your local version directly, so you can continue to use the non-embed functionality.
