### ISSUE TITLE
Use this package with CLI 3.0

### ISSUE THREAD

**Issue by sahilcrawlapps** [Kyon147/laravel-shopify#7]
Hello guys,

I am stuck between the CLI app and this package. Both of them have their pros and cons of using and not using it.

Can you guys guide me to just setup an app with the both of them. I mean how can I implement the this package with the cli 3.0 Shopify app.

There is nothing mentioned in the wiki as well. Is this stable with the cli app ? I am a little confused to use it or not with the app built using shopify cli.

Thanks.

**Comment by Kyon147** [comment]
Hi @sahilcrawlapps 

The wiki is currently still in the parent app here https://github.com/gnikyt/laravel-shopify/wiki

The main question is really why you want to use this app with the Shopify CLI - what are you trying to achieve? 

The wiki explains how to set up this app to use it as it is meant to but there is not documentation for the CLI 3.0 because it's never been conceived to work like that as a hybrid. 

This app scaffolds a shopify app and the CLI 3 does the same thing but both work in different ways. I did a compare in this thread here https://github.com/gnikyt/laravel-shopify/discussions/1211

**Comment by sahilcrawlapps** [comment]
Actually shopify cli template lacks documentation and a lot of good stuff which is provided by this package and not in the cli especially the billing features of this package and webhooks as well.
The motive of being with both of them was to establish the pros of using both. For example it is easy to build new features with the CLI instead of this package and for this package it is easy to build and structure app and manage things with this package.

By the way thanks for the package and you valuable time I got your point.

**Comment by Kyon147** [comment]
Hey @sahilcrawlapps 

That makes sense, the documentation of this package has always been top notch, which is great for people who might be starting out.

The package does take some effort out of the boilerplate, like the webhooks and billing as you mention. Other features if you needed can be added on inside your own app, which is what I tend to do on a case by case basis.

**Comment by sahil0571** [comment]
So it means I can use this package with the cli template right ?

**Comment by Kyon147** [comment]
I have used the Shopify CLI to use the App Embed extension in a recent app that went live on the app store without any issue. So using the CLI is possible with this app from what I have used it for but could not give you a definitive answer as a whole.

**Comment by sahilcrawlapps** [comment]
Ok, Got it at some point. Btw thanks for the reply and maintaining this package.
I don't have that much knowledge about how this package code works and I am new to this But I will surely try to contribute in it.
